### ISSUE TITLE
Fix <url> in pom.xml

### ISSUE THREAD

**Issue by gvlasov** [Suseika/readonly-collections#13]
s/readonly-collections/rocollections/g

**Comment by Suseika** [comment]
@rultor release, tag='0.3.0'

**Comment by Suseika** [comment]
@rultor release, tag=`0.3.0`

**Comment by Suseika** [comment]
@rultor release, tag=`0.3.0`

**Comment by Suseika** [comment]
@rultor release, tag=`0.3.0`

**Comment by gvlasov** [comment]
@rultor release, tag=`0.3.0`

**Comment by Suseika** [comment]
@rultor release, tag=`0.3.0`

**Comment by Suseika** [comment]
@rultor release, tag=`0.3.0`

**Comment by gvlasov** [comment]
@rultor release, tag=`0.3.0`
